### ISSUE TITLE
upstart config file

### ISSUE THREAD

**Issue by reswob10** [MarkBaggett/freq#10]
One of the CentOS 6 servers uses upstart.  Here's the conf file I put in /etc/init/ to run this as a service:
```

description     "Freq Server"
start on filesystem or runlevel [2345]
stop on runlevel [!2345]

respawn

script
      export HOME="/usr/bin"
      echo $$ > /var/run/freqserver.pid
      exec python /opt/freqserver/freq_server.py -ip <IP> <port> /opt/freqserver/english_lowercase.freq
end script

pre-start script
      echo "[`date`] Freq Server starting" >> /var/log/messages
end script

pre-stop script
      echo "[`date`] Freq Server stopping" >> /var/log/messages
end script
```

**Comment by reswob10** [comment]
Some information about using this:  
https://www.digitalocean.com/community/tutorials/the-upstart-event-system-what-it-is-and-how-to-use-it

**Comment by MarkBaggett** [comment]
Thanks.
Althought it doesn't affect the functionality of your upstart config, I noticed your using the english_lowercase.freq dictionary which is associated with the old version of freq.py and freq_server.py.  You might consider an update.  It isn't a seamless replacement.  You may have to change the URL you request.  But it is faster, runs in Python3 and has some improved calculations.

Check out https://www.youtube.com/watch?v=dfrh1FaFUic

I'll add this to the repo.

**Comment by reswob10** [comment]
I actually took your and Justin suggestion to create a new file custom to
our environment.

Definitely increases accuracy
