### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by mertzjames** [MarkBaggett/freq#11]
I'm not sure what your process for contributing to this project is.  I have a few things that I would like to tackle to help out the project, is there a specific process you have in place for doing this, or is it simply fork, make the changes, and then PR the changes?

**Comment by MarkBaggett** [comment]
That’s correct.  I appreciate any pull requests.  

Mark

**Comment by mertzjames** [comment]
ok Cool.  If you don't mind, I'm going to create a `CONTRIBUTE.md` file and reference it in the `README.md` to help others that may be interested in the project.
