### ISSUE TITLE
An always true statement

### ISSUE THREAD

**Issue by mertzjames** [MarkBaggett/freq#15]
On the line below, there is never a case where the key will be longer than a one char string, and therefore the second statement will always evaluate to true:

https://github.com/MarkBaggett/freq/blob/master/freq.py#L23

```python
if self.parent.ignore_case and (key.islower() or key.isupper()):
```

can, therefore, be changed to;

```python
if self.parent.ignore_case:
```

**Comment by MarkBaggett** [comment]
Keys can be numbers or special characters.  

Mark

**Comment by mertzjames** [comment]
if the intention is to check is the key is an alpha, then you should probably use `key.isalpha()` instead:

https://docs.python.org/2/library/stdtypes.html#str.isalpha
https://docs.python.org/3/library/stdtypes.html#str.isalpha

**Comment by MarkBaggett** [comment]
I am aware of isalpha.   Thanks
