### ISSUE TITLE
duplicate words can be tallied

### ISSUE THREAD

**Issue by mertzjames** [MarkBaggett/freq#17]
if a new word is added to the table using `tall_str` and that word has already been processed, then that can cause duplicate data essentially.  The tool should keep a set of already processed words and check that there aren't duplicates created.  

A simple solution could be to keep a `set()` internal to `FreqCounter` and check that the word hasn't already been processed.

**Comment by MarkBaggett** [comment]
The tool processes duplicate by design.  Word frequency is relevant data.  

Mark
