### ISSUE TITLE
get 2 scores returned

### ISSUE THREAD

**Issue by gnomefish** [MarkBaggett/freq#18]
Hi Mark,

I just pulled the so-frreqserver (which runs the same command line as yours)

docker pull securityonionsolutions/so-freqserver
docker run -p 10004:10004 securityonionsolutions/so-freqserver

How come it returns 2 scores when I query it? When I installed freq_server from scratch I never had that.

root@ubuntu:/opt# curl http://localhost:10004/measure/crimsoncore.be
(10.0239, 8.6545)

Cheers,
Luk

**Comment by MarkBaggett** [comment]
If the README is not a sufficient explanation you I recommend this video. 

https://youtu.be/dfrh1FaFUic

Mark

**Comment by gnomefish** [comment]
Hey Mark, yeah this is great - thanks so much!
Luk

**Comment by MarkBaggett** [comment]
I think you probably got the code from the SANS blueteam fork.   They fork it so it stays synchronized with the courseware.  I think it’s a few revisions behind.
