### ISSUE TITLE
Could use a lot of PEP8 style refactoring

### ISSUE THREAD

**Issue by cwkingjr** [MarkBaggett/freq#2]
This looks like a very cool project. One thing I noticed when reviewing the code is that there are numerous Python coding style violations. Tools like flake8, pylint, and black can help a lot with this. 

https://www.python.org/dev/peps/pep-0008/

https://pypi.org/project/flake8/
https://github.com/PyCQA/pylint
https://github.com/ambv/black

**Comment by MarkBaggett** [comment]
.

**Comment by mertzjames** [comment]
was the decision not to do this?  I'd be willing to work on this to help out with it.

**Comment by MarkBaggett** [comment]
Go for it!   I appreciate it.  

Mark
