### ISSUE TITLE
package reorg

### ISSUE THREAD

**Issue by mertzjames** [MarkBaggett/freq#21]
Hey Mark, 

Over the next couple of weeks I wanted to work on this project.  One of the things I'd like to do is reorg the structure of the code here to something like this:

```
/root (freq)
- freq (source)
- bin (.exe, systemd, upstart, etc)
- test
- setup.py
- README.md
```

This would organize the code a little better, allow for package install and upload to pip, and creating better installers for local systems.  What are your thoughts on this?

**Comment by MarkBaggett** [comment]
Hi James.  
Nice to hear from you again. Sure!!.   I welcome the pushes.   I am knee deep in a few other project so it might take a little for me to test and merge them but It’s mostly a reorg and not many code changes I should be able to make that happen reasonably quick. 

Mark
