### ISSUE TITLE
Combining freq score with Alexa top 1M

### ISSUE THREAD

**Issue by Cyb3r-Monk** [MarkBaggett/freq#5]
Hi, 

Is it possible to add new feature that checks order of the domain in Alexa? This way, we can compare the freq score with Alexa and optimize/reduce false positives. It would be perfect if we can query just for the freq score, Alexa order or both.

**Comment by MarkBaggett** [comment]
Hi.  That feature (and a few others) are implemented in a tool I released called domain_stats.  

https://github.com/MarkBaggett/domain_stats/

Mark

**Comment by Cyb3r-Monk** [comment]
Thanks! I'll  use it as a different API server then.
