### ISSUE TITLE
Error on raise exception

### ISSUE THREAD

**Issue by mbrancato** [MarkBaggett/freq#6]
There seems to be a typo on the following line, but this line would only cause an if the frequency table specified could not be found.

Technically it is valid syntax, but the object does not exist.

https://github.com/MarkBaggett/freq/blob/48010fd45a11d4257e1a758b49193a30addd9442/freq_server.py#L201

**Comment by MarkBaggett** [comment]
Good catch.  Thanks.  I’ll fix it.  

Mark

**Comment by MarkBaggett** [comment]
Fixed.  Thanks.
